# -*- coding: utf-8 -*-
# !/usr/bin/env python

SEEDBOX_DOMAIN_NAME = ""
SEEDBOX_USER_NAME = ""
SEEDBOX_PASSWD = ""

TRELLO_API_KEY = ""
TRELLO_SERVER_TOKEN = ""
TRELLO_OAUTH_SECRET = ""

TWITTER_API_KEY = ""
TWITTER_API_SECRET_KEY = ""
TWITTER_ACCESS_TOKEN = ""
TWITTER_ACCESS_TOKEN_SECRET = ""

STEAM_API_KEY = ""

REDDIT_USERNAME = ""
REDDIT_PASSWORD = ""
REDDIT_APP_CLIENT_KEY = ""
REDDIT_API_SECRET_KEY = ""

POCKET_CONSUMER_KEY = ""
POCKET_USERNAME = ""
POCKET_PASSWORD = ""
